create table if not exists public.hmi_trends (
  id bigint generated by default as identity primary key,
  timestamp timestamptz not null default now(),
  inverter_power_kw numeric(10, 2) not null default 0,
  solar_radiation numeric(10, 2) not null default 0,
  pump1_head_m numeric(10, 2) not null default 0,
  pump2_head_m numeric(10, 2) not null default 0,
  pump1_flow_lpm numeric(10, 2) not null default 0,
  pump2_flow_lpm numeric(10, 2) not null default 0,
  total_flow_lpm numeric(10, 2) not null default 0,
  ambient_temp_c numeric(10, 2) not null default 0
);

alter table public.hmi_trends enable row level security;

create table if not exists public.app_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text unique not null,
  full_name text,
  role text not null default 'operator',
  site_name text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.handle_new_app_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.app_users (user_id, email, full_name, role, site_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    coalesce(new.raw_user_meta_data ->> 'role', 'operator'),
    coalesce(new.raw_user_meta_data ->> 'site_name', '')
  )
  on conflict (user_id) do update
  set
    email = excluded.email,
    full_name = excluded.full_name,
    role = excluded.role,
    site_name = excluded.site_name,
    updated_at = now();

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row
execute procedure public.handle_new_app_user();

alter table public.app_users enable row level security;

insert into public.app_users (user_id, email, full_name, role, site_name)
select
  u.id,
  u.email,
  coalesce(u.raw_user_meta_data ->> 'full_name', ''),
  coalesce(u.raw_user_meta_data ->> 'role', 'operator'),
  coalesce(u.raw_user_meta_data ->> 'site_name', '')
from auth.users u
on conflict (user_id) do nothing;

drop policy if exists "Allow public read for hmi trends" on public.hmi_trends;
drop policy if exists "Allow public insert for hmi trends" on public.hmi_trends;
drop policy if exists "Allow authenticated read for hmi trends" on public.hmi_trends;
create policy "Allow authenticated read for hmi trends"
on public.hmi_trends
for select
to authenticated
using (true);

drop policy if exists "Allow authenticated insert for hmi trends" on public.hmi_trends;
create policy "Allow authenticated insert for hmi trends"
on public.hmi_trends
for insert
to authenticated
with check (true);

drop policy if exists "Users can read own profile" on public.app_users;
create policy "Users can read own profile"
on public.app_users
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can update own profile" on public.app_users;
create policy "Users can update own profile"
on public.app_users
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
